export const initiallocations = ["Example 1", "Example 2", "Example 3"];
export const listOfTypeslocations = [
  "Fast Food locations",
  "Casual Dining locations",
  "Fine Dining locations",
  "Cafes",
  "Bistros",
  "Pizzerias",
  "Steakhouses",
  "Buffet locations",
  "Food Trucks",
  "Gastropubs",
  "Brasseries",
  "Diners",
  "Sushi Bars",
  "Taco Stands",
  "Ice Cream Parlors",
  "Barbecue Joints",
  "Delis (Delicatessens)",
  "Tea Houses",
  "Patisseries",
  "Wine Bars",
  "Ethnic locations (e.g., Italian, Mexican, Indian)",
  "Farm-to-Table locations",
  "Fusion locations",
  "Pop-up locations",
  "Bakeries",
];
